<div id="messages">
    <div class="message"> This image is exist gallery. Must clear image in gallery before delete.
        <button class="primary">OK</button>
    </div>
</div>
<script type="text/javascript">// <![CDATA[
    require([
            'jquery',
            'Magento_Ui/js/modal/alert'
        ],
        function($, alert) {
            $('#messages').on('click', 'button.primary', function(event){
                alert({
                    content: $(event.target).parent().text()
                })
            })
        }
    );
    // ]]></script>
</div>